import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Sidebar } from "@/features/Navigation/components/Sidebar";
import { Dashboard } from "@/features/Dashboard/components/Dashboard";
import { Social } from "@/features/Social/components/Social";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.baseComponent}>
          <Sidebar></Sidebar>
        </div>

        <div className={styles.baseComponent}>
          <Dashboard></Dashboard>
        </div>

        <div className={styles.baseComponent}>
          <Social></Social>
        </div>
      </main>
    </>
  );
}
